config/routes.rb
Rails.application.routes.draw do

  root 'users#login'

  get 'login', to: "users#login", as: 'login'

  get 'signup', to: "users#signup", as: 'signup'

  post 'login', to: "users#attempt_login"

  get 'about', to: "main#about", as: 'about'

  post 'signup', to: "users#create"

  get 'home', to: "users#home", as: 'home'

  delete 'logout', to: "users#logout", as: "logout"

  post 'main', to: "comments#create", as: "comment"

  get '/main', to: 'main#map', as: 'map'

  get '/search', to: 'main#search', as: 'search'

  post '/save', to: 'main#save_hood', as: 'save'

  get '/favorites', to: 'main#favorites', as: 'favorites'

  get '/checkfav', to: 'main#check_fav', as: 'check_fav'

  post '/favorites', to: 'main#add_fav', as: "add_fav"

  #### RAKE ROUTES ####

#    Prefix Verb   URI Pattern          Controller#Action
#      root GET    /                    users#login
#     login GET    /login(.:format)     users#login
#    signup GET    /signup(.:format)    users#signup
#           POST   /login(.:format)     users#attempt_login
#     about GET    /about(.:format)     main#about
#           POST   /signup(.:format)    users#create
#      home GET    /home(.:format)      users#home
#    logout DELETE /logout(.:format)    users#logout
#  main_map GET    /main/map(.:format)  main#map
#   comment POST   /main(.:format)      comments#create
#       map GET    /main(.:format)      main#map
#    search GET    /search(.:format)    main#search
#      save POST   /save(.:format)      main#save_hood
# favorites GET    /favorites(.:format) main#favorites
#   add_fav PATCH  /favorites(.:format) main#add_fav

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/hood.rb
class Hood < ActiveRecord::Base
  has_many :users, through: :searches
  has_many :searches
  has_many :comments, as: :commentable

  validates_uniqueness_of :name, scope: :city
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
  belongs_to :hood

  validates :hood_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hoods, through: :searches
  has_many :searches
  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :confirm_logged_in
  def create
    find_commentable.comments.build(comment_params.merge user_id: session[:user_id]).save
    if @comment.save
      flash[:success] = "Congrats! You added a comment, bro."    
    else
      flash[:alert] = "No comment for you."      
    end
    redirect_to :back, flash: {success: "Thanks for the comment."}
  end

  def show_on_click
  end

  def edit 
  end

  def delete
    comment = Comment.find(params[:id]).destroy
    redirect_to :back
  end
  private 
    def comment_params
      params.require(:comment).permit(:content)
    end
    def find_commentable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
      nil
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  require 'json'

  def map
    @found_user = User.find session[:user_id]
  end

  def about
    @found_user = User.find session[:user_id]
  end

  def search
    city = params[:city]
    wu_city = params[:city].squish.downcase.tr(" ","_")
    state = params[:state]
    neighborhood = params[:neighborhood]
    requestZillow = Typhoeus::Request.new(
      "https://www.zillow.com/webservice/GetDemographics.htm?zws-id=" + ENV["ZILLOW_API_KEY"]+ "&",
      method: :get,
      params: {
        city: city,
        neighborhood: neighborhood,
        state: state
      }
    )
    requestZillow.run
    @zillowData = JSON.parse(Hash.from_xml(requestZillow.response.body).to_json)
    requestWeather = Typhoeus::Request.new(
      "https://api.wunderground.com/api/" + ENV["WEATHER_UNDERGROUND_API_KEY"] + "/geolookup/q/#{state}/#{wu_city}.json",
      method: :get
    )
    requestWeather.run
    @weatherData = JSON.parse(requestWeather.response.body)
    respond_to do |format|
      format.html
      format.json { render json: {
        :zillowData => @zillowData,
        :weatherData => @weatherData 
        }
      }
    end
  end

  def save_hood
    name = params[:name]
    city = params[:city]
    state = params[:state]
    @hood = Hood.create(name:name, city:city, state:state)
    render nothing: true
  end 

  def favorites
    @user = User.find session[:user_id]
    @fav_hoods = []
    favorites = @user.searches
    favorites.each do |favorite|
      if favorite.is_fav
        fav = Hood.find favorite.hood_id
        @fav_hoods << fav
      end
    end
  end

  def add_fav 
    user = User.find session[:user_id]
    hood = Hood.find_by name: params[:neighborhood], city: params[:city]
    @fav = Search.find_by user_id:user.id, hood_id:hood.id
    if @fav != nil
      if @fav.is_fav == true
        @fav.update_attributes(is_fav:false)
        respond_to do |format|
          format.json { render json: @fav }
        end
      else
        @fav.update_attributes(is_fav:true)
        respond_to do |format|
          format.json { render json: @fav }
        end
      end
    else
      @fav = Search.create(user_id:user.id, hood_id:hood.id, is_fav:true)
      respond_to do |format|
        format.json { render json: @fav }
      end
    end
  end

  def check_fav
    user = User.find session[:user_id]
    hood = Hood.find_by name: params[:neighborhood], city: params[:city]
    @fav = Search.find_by user_id:user.id, hood_id:hood.id
    if @fav != nil
      if @fav.is_fav == true
        respond_to do |format|
          format.json { render json: @fav }
        end
      else
        render nothing: true
      end
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :prevent_login_signup, only: [:signup, :login]

  def signup
    @user = User.new
  end

  def login
  end 

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.find_by_username params[:username]
      if found_user
        authorized_user = found_user.authenticate params[:password]
      end
    end
    if !found_user
      flash.now[:notice] = "Wrong username or password. Please try again."
      render :login
    elsif !authorized_user
      flash.now[:notice] = "Wrong username or password. Please try again."
      render :login
    else
      session[:user_id] = authorized_user.id
      redirect_to map_path
    end
  end


  def home
    user_id = session[:user_id]
    @found_user = User.find(user_id)
    redirect_to map_path
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to map_path
    else
      flash.now[:notice] = "Username and Password can't be blank."
      render :signup
    end
  end

private 
  def prevent_login_signup
    if session[:user_id]
      redirect_to map_path
    end
  end
  
  def user_params
    params.require(:user).permit(:username, :password, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Good Hoods</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV[GMAPS_API_KEY]}"></script>
  <!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBQAm-55TNoeLbXvWEYRGf3tOzhFcH-Y5k"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<style type="text/css">

  .my_notice {
    border-radius: 0px;
    border: 0px;
    background-color: rgba(255, 102, 102, 1);
    color: white;
  }
  .my_alert {
    background-color: rgba(255, 102, 102, 1);
    color: white;
    border: 0px;
  }

</style>

</head>

<body class = "container-fluid text-center">

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning my_notice" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger my_alert" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/main/about.html.erb
<style>
  body { 
  padding-top: 60px; 
  }
  
  #left {
    display: inline-block;
    text-align: left;
  }

  .mynav {
  background-color: rgba(255, 102, 102, 1);
  color: #888;
  display: block;
  margin: 0;
  overflow: hidden;
  width: 100%; 
  }

  .mynav ul {
    text-align: right;
    margin: 0px;
    padding: 11px;
  }

  .mynav ul li {
      padding-left: 30px;
      color: white;
      display: inline-block;
      list-style-type: none;
      
      -webkit-transition: all 0.2s;
        -moz-transition: all 0.2s;
        -ms-transition: all 0.2s;
        -o-transition: all 0.2s;
        transition: all 0.2s; 
  }

  .mynav ul li a {
      color: white;
      text-decoration: underline;
  }

  .mynav ul li a:hover {
      color: rgba(255, 102, 102, 1);
      background-color: rgba(255, 255, 255, 1);
      text-decoration: none;
  }

  .floatleft {
    float: left;
    margin-left: -30px;
  }

  .floatright {
    float: right;
    padding-top: 5px;
  }

  a {
    color: rgba(255, 102, 102, 0.9);
  }
  
  a:hover {
    color: rgba(255, 102, 102, 0.9);
    background: rgba(255, 102, 102, 0.2);
    text-decoration: none;
  }

  #nohover a:hover {
    color: transparent;
    background: transparent;
    text-decoration: none;
  }
  </style>
  
<nav class="navbar navbar-default navbar-fixed-top mynav">
  <div class="container">
    <ul>
    <div class="floatleft"><li id="nohover"><a href="/"><%= image_tag("header_icon.png") %></a></li></div>
    <div class="floatright"><li>Logged in as <i><%= @found_user.username %></i></li>
    <li><%= link_to "Favorites", favorites_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Sign Out", logout_path, method: :delete %></li></div>
    </ul>
  </div>
</nav>

<div class="container-fluid">

  <div class="row">
    <div class="col-md-12">
      <ol style="visibility:hidden;">
        <li>&nbsp;</li>
      </ol>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <p class="text-left lead">
        We built Good Hoods to let you and other prospective home buyers quickly and easily research neighborhoods where you might one day live.

        We consolidate data from Google Maps, Zillow and The Weather Underground to give you pertinent information about specific neighborhoods you’re interested in, and to save you time to do other things – like secure a home loan! 
      </p>
    </div>
    <div class="col-md-2"></div>
  </div>  

  <div class="row">
    <div class="col-md-12">
      <ol style="visibility:hidden;">
        <li>&nbsp;</li>
        <li>&nbsp;</li>
      </ol>
      <p class="text-center lead">
        Good Hoods was built at <a href="http://generalassemb.ly">General Assembly</a> in San Francisco by:
      </p><br />
    </div>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-2 lead">
      <p><a href="http://github.com/brent1x"><%= image_tag("brent.png", size: "150x150") %></a></p><br />
      <p><a href="http://github.com/brent1x">@brent1x</a></p>
    </div>
    <div class="col-lg-2 lead">
      <p><a href="http://github.com/calvinkw1"><%= image_tag("calvin.png", size: "150x150") %></a></p><br />
      <p><a href="http://github.com/calvinkw1">@calvinkw1</a></p>
    </div>
    <div class="col-lg-2 lead">
      <p><a href="http://github.com/doylemcpoyle"><%= image_tag("pat.png", size: "150x150") %></a></p><br />
      <p><a href="http://github.com/doylemcpoyle">@doylemcpoyle</a></p>
      </div>
    <div class="col-lg-2 lead">
      <p><a href="http://github.com/MichaelPoP"><%= image_tag("mike.png", size: "150x150") %></a></p><br />
      <p><a href="http://github.com/MichaelPoP">@michaelpop</a></p>
    </div>
    <div class="col-lg-2"></div>
  </div>

</div>

</div>

app/views/main/favorites.html.erb
<%= stylesheet_link_tag 'map', media: 'all', 'data-turbolinks-track' => true %>

  <nav class="navbar navbar-default navbar-fixed-top mynav">
    <div class="container">
      <ul>
      <div class="floatleft"><li id="nohover"><a href="/"><%= image_tag("header_icon.png") %></a></li></div> 
      <div class="floatright"><li>Logged in as <i><%= @user.username %></i></li>
      <li><%= link_to "Favorites", favorites_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Sign Out", logout_path, method: :delete %></li></div>
      </ul>
    </div>
  </nav>

<div class="container-fluid">

  <div class="row">
    <div class="col-xs-12">
      <div class="text-center">
        <h2><%= @user.username %>'s Favorited Hoods</h2>
      </div>
    </div>
  </div>

  <div class="row spacer"></div>
  
  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Favorite Neighborhoods</th>
            <th>City</th>
            <th>State</th>
          </tr>
        </thead>
        <tbody>
          <% @fav_hoods.each do |fav| %>
            <tr class="text-left">
              <td><%= fav.name %></td>
              <td><%= fav.city %></td>
              <td><%= fav.state %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-xs-3"></div>
  </div>
</div>

app/views/main/map.html.erb
<%= stylesheet_link_tag 'map', media: 'all', 'data-turbolinks-track' => true %>

  <nav class="navbar navbar-default navbar-fixed-top mynav">
    <div class="container">
      <ul>
      <div class="floatleft"><li id="nohover"><a href="javascript:history.go(0)"><%= image_tag("header_icon.png") %></a></li></div> 
      <div class="floatright"><li>Logged in as <i><%= @found_user.username %></i></li>
      <li><%= link_to "Favorites", favorites_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><a href="#" data-toggle="modal" data-target="#myModal">Help</a></li>
      <li><%= link_to "Sign Out", logout_path, method: :delete %></li></div>
      </ul>
    </div>

  </nav>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">How to use Good Hoods</h4>
      </div>
      <div class="modal-body text-left">
        <p>Good Hoods lets you search for information about neighborhoods you're interested in.</p>
        <p>Type in a City and State to pull up a listing of all the neighborhoods in that city.</p>
        <p>Click on a neighborhood and we'll display information from that neighborhood that we've pulled from a variety of services, like Google Places, Zillow and The Weather Underground.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
 
<div class="container-fluid">

  <div class="row">
    <div class="col-lg-12">
      <div class="text-center">
          <%= form_tag search_path, method: "get", id:"search-input", class:"controls" do %>
          <%= label_tag(:city, "City: ") %>
          <%= text_field_tag(:city) %>
          <%= label_tag(:state, "State: ") %>
          <%= text_field_tag(:state) %>
          <%= submit_tag("Search Hoods", :class => "btn-search") %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row spacer">

    <div class="col-xs-3 hood-div">
        <p id="info-box"></p>
        <ul id="hoods">
        </ul>
    </div>

    <div class="col-xs-6">
      <div id="map-canvas"></div>
    </div>

    <div class="col-xs-3 info-div">
      <p class="text-left fav"><a><span class="glyphicon glyphicon-star-empty" id="fav" aria-hidden="true"></span></a>&nbsp; Favorite</p>
      <div class="text-left" id="people"></div>
      <div class="text-left" id="city-summary"></div>
      <div class="text-left" id="characteristics"></div>
      <div class="text-left" id="ages"></div>
      <div class="text-left" id="kids"></div>
      <div class="text-left" id="relationships"></div>
      <div class="text-left" id="charts"></div>
      <div class="text-left" id="weather"></div>
    </div>  

    <div class="col-xs-1"></div>
  </div>

</div>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/login.html.erb
<style>
  body {
    color: #ffffff;
    }
 
  input {
    color: #fff;
    border-radius: 5px;
    border: 0;
    height: 35px; 
    background-color: rgba(255, 102, 102, 0.9);
    margin: 2px;
    width: 140px;
    padding: 5px;
    -webkit-box-sizing: border-box; /* Safari/Chrome, other WebKit */
    -moz-box-sizing: border-box;    /* Firefox, other Gecko */
    box-sizing: border-box;         /* Opera/IE 8+ */
    }

  input::-webkit-input-placeholder {
     color: white;
  }

  .override {
    color: white;
    width: 70px;
  }
  
  a {
    color: rgba(255, 102, 102, 0.9);
  }
  
  a:hover {
    color: rgba(255, 102, 102, 0.9);
    background-color: rgba(255, 102, 102, 0.2);
    padding: 3px;
    text-decoration: none;
  }

  .my-button1 {
    margin-top: -2px;
    border-radius: 5px;
    /*opacity: 0;*/
   /* background-color: rgba(255, 102, 102, 0.0);
    border: 1px solid rgba(255, 102, 102, 0.9);*/
  }

  .my-input {
     background-color: rgba(255, 102, 102, 0.0);
     border: 1px solid rgba(255, 102, 102, 0.9);
  }

</style>

<%= javascript_include_tag "bgcycle", "data-turbolinks-track" => true %>

        <script type="text/javascript">
            $(document).ready(function() {
                $("body").backgroundCycle({
                    imageUrls: [
                        "<%= asset_path('bg5_low.jpg') %>", 
                        "<%= asset_path('bg2.jpg') %>",
                        "<%= asset_path('bg3.jpg') %>",
                        "<%= asset_path('bg4.jpg') %>",
                        "<%= asset_path('bg1.jpg') %>"
                    ],
                    fadeSpeed: 1000,
                    duration: 5000,
                    backgroundSize: SCALING_MODE_COVER
                });
            });
        </script>

<div class="container-fluid">

<div class="row">
  <div class="col-md-12">
    <ol style="visibility:hidden;">
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= image_tag("header.png", size: "650x75") %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ol style="visibility:hidden;">
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_tag(login_path) do %>
    <%= text_field_tag(:username, params[:username], placeholder: "Username", class: "my-input", autofocus: true)%>
    <%= password_field_tag(:password, nil, placeholder: "Password", class: "my-input") %>
    <%= submit_tag("Go", class: "my-button1") %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ol style="visibility:hidden;">
      <li>&nbsp;</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Don't have an account? Sign up here.", signup_path %>
  </div>
</div>

</div>

app/views/users/signup.html.erb
<style>
  body {
    color: #ffffff;
    }

  input {
    color: #fff;
    border-radius: 5px;
    border: 0;
    height: 35px; 
    background-color: rgba(255, 102, 102, 0.9);
    margin: 2px;
    width: 140px;
    padding: 5px;
    -webkit-box-sizing: border-box; /* Safari/Chrome, other WebKit */
    -moz-box-sizing: border-box;    /* Firefox, other Gecko */
    box-sizing: border-box;         /* Opera/IE 8+ */
    }

  input::-webkit-input-placeholder {
     color: white;
  }

  .my-button {
    margin-top: -2px;
    border-radius: 5px;
    /*opacity: 0;*/
   /* background-color: rgba(255, 102, 102, 0.0);
    border: 1px solid rgba(255, 102, 102, 0.9);*/
  }

  .my-button:hover {
    color: white;
  }
  
  a {
    color: rgba(255, 102, 102, 0.9);
  }
  
  a:hover {
    color: rgba(255, 102, 102, 0.9);
    background-color: rgba(255, 102, 102, 0.2);
    padding: 3px;
    text-decoration: none;
  }

  .simple_form div.input {
  display: inline-block;
  margin-left: 0px;
  }

  .simple_form div.button {
  display: inline-block;
  margin-left: 0px;
  }

  .inputSign {
     background-color: rgba(255, 102, 102, 0.0);
     border: 1px solid rgba(255, 102, 102, 0.9);
  }

</style>

<%= javascript_include_tag "bgcycle", "data-turbolinks-track" => true %>

        <script type="text/javascript">
            $(document).ready(function() {
                $("body").backgroundCycle({
                    imageUrls: [
                        "<%= asset_path('bg5_low.jpg') %>", 
                        "<%= asset_path('bg2.jpg') %>",
                        "<%= asset_path('bg3.jpg') %>",
                        "<%= asset_path('bg4.jpg') %>",
                        "<%= asset_path('bg1.jpg') %>"
                    ],
                    fadeSpeed: 1000,
                    duration: 5000,
                    backgroundSize: SCALING_MODE_COVER
                });
            });
        </script>

<div class="container-fluid">

<div class="row">
  <div class="col-md-12">
    <ol style="visibility:hidden;">
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= image_tag("header.png", size: "650x75") %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ol style="visibility:hidden;">
      <li>&nbsp;</li>
      <li>&nbsp;</li>
      <li>&nbsp;</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= simple_form_for(@user, url: signup_path) do |f|%>
    <%= f.input(:username, autofocus: true, placeholder: 'Username', label: false, :input_html => {:class => 'inputSign'}) %>
    <%= f.input(:password, placeholder: 'Password', label: false, :input_html => {class: 'inputSign'}) %>
    <%= f.input(:name, placeholder: 'Name', label: false, :input_html => {class: 'inputSign'}) %>
    <%= f.input(:email, placeholder: 'Email', label: false, :input_html => {class: 'inputSign'}) %>
    <%= f.button(:submit, "Sign Up", class: "my-button") %>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ol style="visibility:hidden;">
      <li>&nbsp;</li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Already have an account? Log in here.", login_path %>
  </div>
</div>

</div>